#
# temporary workaround for this bug:
#   https://github.com/drone/drone/issues/2390
clone:
  git:
    image: plugins/git:next
    pull: true
#
# end workaround
#

pipeline:
  install:
    image: node:10
    commands:
      - npm ci
  audit:
    image: node:10
    commands:
      - npm audit
  deploy:
    image: node:10
    commands:
      - echo "//registry.npmjs.org/:_authToken=$${NPM_DEPLOY_TOKEN}" > ~/.npmrc
      - echo "unsafe-perm=true" >> ~/.npmrc
      - npm publish
    secrets:
      - npm_deploy_token
    when:
      event: tag
      branch:
        - include: [ v* ]
